### ISSUE TITLE
Generating new datasets

### ISSUE THREAD

**Issue by josephwinston** [hongzimao/deeprm#1]
In the [paper](http://people.csail.mit.edu/hongzi/content/publications/DeepRM-HotNets16.pdf), there is a discussion of the synthetic database.  If I want to use a different database that reflects my workload, I think that I need to create my own copy of `generate_sequence_work`.  Is this the correct place to make the change?

**Comment by hongzimao** [comment]
It is correct. `generate_sequence_work` calls `dist()` to generate the synthetic workload. The code has normal distribution (`normal_dist`) and bi-model distribution (`bi_model_dist`) provided. One way to reflect your workload is to add another distribution function similar to these. Hope this helps.

**Comment by josephwinston** [comment]
Thanks.  I'll start working on modeling my workflow.
