### ISSUE TITLE
RL agent results 

### ISSUE THREAD

**Issue by ahmadreza9** [hongzimao/deeprm#10]
Hello sir
I converted your code, but now I need to be sure my conversion is true. Could you insert some picture of your results(Monte Carlo) which you print in your code (iteration, numtrajs, numtimesteps, loss,...)

**Comment by ahmadreza9** [comment]
I ask this because of training time

**Comment by hongzimao** [comment]
I think someone posted the log of monitoring before: #2

**Comment by ahmadreza9** [comment]
Your suggestion related to supervised learning  but I need minimum parameters and logs (iteration, numtrajs, numtimesteps, loss,...) for pg_re_single_core  which takes more training time

**Comment by hongzimao** [comment]
If you have the setup ready, could you run one and paste the log? We can check if the numbers make sense in the bulk part. Our lab machine right now is busy running other jobs -- might not be accurate to benchmark runtime at this point. Thanks!

**Comment by ahmadreza9** [comment]
My setup is:
end=all_done
repre=image
render=false
distribution=bi_model
network_input_height=20
network_input_width=224
network_output_dim=11
num_ex=10
num_seq_per_batch=20
episode_max_length=200
simu_len=100
num_nw=10
new_job_rate=0.3
`Load on # 0 resource dimension is 0.5548
Load on # 1 resource dimension is 0.6606000000000001
network_input_height= 20
network_input_width= 224.0
network_output_dim= 11
Preparing for data...
Load on # 0 resource dimension is 0.5548
Load on # 1 resource dimension is 0.6606000000000001



=============== 0 ===============
---------- Tetris -----------
total discount reward : 	 -309.16223776223774
---------- SJF -----------
total discount reward : 	 -122.80221445221444
---------- Random -----------
total discount reward : 	 -298.46620046620023



=============== 1 ===============
---------- Tetris -----------
total discount reward : 	 -105.80952380952382
---------- SJF -----------
total discount reward : 	 -94.06263736263732
---------- Random -----------
total discount reward : 	 -186.48095238095252



=============== 2 ===============
---------- Tetris -----------
total discount reward : 	 -183.29329004329014
---------- SJF -----------
total discount reward : 	 -100.8809523809523
---------- Random -----------
total discount reward : 	 -419.2311688311685



=============== 3 ===============
---------- Tetris -----------
total discount reward : 	 -122.47016317016313
---------- SJF -----------
total discount reward : 	 -78.53170163170171
---------- Random -----------
total discount reward : 	 -233.54090909090914



=============== 4 ===============
---------- Tetris -----------
total discount reward : 	 -236.37665667665686
---------- SJF -----------
total discount reward : 	 -78.49746919746914
---------- Random -----------
total discount reward : 	 -254.66500166500177



=============== 5 ===============
---------- Tetris -----------
total discount reward : 	 -296.3734598734601
---------- SJF -----------
total discount reward : 	 -188.1838827838828
---------- Random -----------
total discount reward : 	 -292.4598568098567



=============== 6 ===============
---------- Tetris -----------
total discount reward : 	 -66.33333333333337
---------- SJF -----------
total discount reward : 	 -53.43333333333334
---------- Random -----------
total discount reward : 	 -173.28333333333322



=============== 7 ===============
---------- Tetris -----------
total discount reward : 	 -141.6388278388279
---------- SJF -----------
total discount reward : 	 -130.62820512820522
---------- Random -----------
total discount reward : 	 -196.9703296703295



=============== 8 ===============
---------- Tetris -----------
total discount reward : 	 -75.83982683982684
---------- SJF -----------
total discount reward : 	 -74.33982683982686
---------- Random -----------
total discount reward : 	 -236.93463203463193



=============== 9 ===============
---------- Tetris -----------
total discount reward : 	 -160.46666666666667
---------- SJF -----------
total discount reward : 	 -100.12424242424244
---------- Random -----------
total discount reward : 	 -239.2090909090908







Iteration: 	 0
NumTrajs: 	 200
NumTimesteps: 	 32549
Loss:     	 0.1269063800573349
MaxRew: 	 -199.90956376956376
MeanRew: 	 -257.43755677655673 +- 63.18571158682983
MeanSlowdown: 	 8.095057915739412
MeanLen: 	 162.745 +- 13.351403484278348
MeanEntropy 	 2.397886
Elapsed time	 106.06723022460938 seconds
-----------------
-----------------
Iteration: 	 1
NumTrajs: 	 200
NumTimesteps: 	 32898
Loss:     	 0.1925097107887268
MaxRew: 	 -204.07878954378955
MeanRew: 	 -261.049011072261 +- 57.66479504130108
MeanSlowdown: 	 8.206078551195306
MeanLen: 	 164.49 +- 13.619100557672668
MeanEntropy 	 2.3972197
Elapsed time	 98.67690372467041 seconds
-----------------
Iteration: 	 2
NumTrajs: 	 200
NumTimesteps: 	 32910
Loss:     	 0.1276756227016449
MaxRew: 	 -203.059632034632
MeanRew: 	 -266.99093198468194 +- 59.64957418897762
MeanSlowdown: 	 8.394288999636847
MeanLen: 	 164.55 +- 14.931761450009843
MeanEntropy 	 2.3913114
Elapsed time	 100.0682418346405 seconds
-----------------
-----------------
Iteration: 	 3
NumTrajs: 	 200
NumTimesteps: 	 33470
Loss:     	 0.13244816660881042
MaxRew: 	 -218.35205128205126
MeanRew: 	 -282.0441643356642 +- 66.60710107340651
MeanSlowdown: 	 8.855150677656205
MeanLen: 	 167.35 +- 15.239996719159752
MeanEntropy 	 2.3685246
Elapsed time	 100.70498061180115 seconds
-----------------
-----------------
Iteration: 	 4
NumTrajs: 	 200
NumTimesteps: 	 34776
Loss:     	 -0.26251670718193054
MaxRew: 	 -234.50364968364966
MeanRew: 	 -310.485441058941 +- 75.55222335014817
MeanSlowdown: 	 9.749522025067222
MeanLen: 	 173.88 +- 15.928452529985453
MeanEntropy 	 2.3226619
Elapsed time	 108.5326337814331 seconds
-----------------
Iteration: 	 5
NumTrajs: 	 200
NumTimesteps: 	 36498
Loss:     	 -0.5769447684288025
MaxRew: 	 -255.85012987012988
MeanRew: 	 -351.746344072594 +- 84.08358097680957
MeanSlowdown: 	 10.906615904032172
MeanLen: 	 182.49 +- 16.03433503454384
MeanEntropy 	 2.1659942
Elapsed time	 112.69460654258728 seconds
-----------------
-----------------
Iteration: 	 6
NumTrajs: 	 200
NumTimesteps: 	 38392
Loss:     	 -0.7190216183662415
MaxRew: 	 -303.35084748584757
MeanRew: 	 -411.73005760905755 +- 89.4006900403393
MeanSlowdown: 	 11.768114982875948
MeanLen: 	 191.96 +- 12.692454451365977
MeanEntropy 	 2.0376923
Elapsed time	 130.7051191329956 seconds
-----------------
-----------------
Iteration: 	 7
NumTrajs: 	 200
NumTimesteps: 	 39488
Loss:     	 -1.1476973295211792
MaxRew: 	 -340.6637928737929
MeanRew: 	 -480.5774826839828 +- 90.47000124859412
MeanSlowdown: 	 11.150918905930217
MeanLen: 	 197.44 +- 7.323004847738393
MeanEntropy 	 1.8062774
Elapsed time	 125.56303191184998 seconds
-----------------
-----------------
Iteration: 	 8
NumTrajs: 	 200
NumTimesteps: 	 39807
Loss:     	 -1.565395474433899
MaxRew: 	 -422.8654412254412
MeanRew: 	 -549.875601898102 +- 98.59122356069449
MeanSlowdown: 	 9.951740632506358
MeanLen: 	 199.035 +- 4.735374853166326
MeanEntropy 	 1.5910137
Elapsed time	 137.8277566432953 seconds
-----------------
-----------------
Iteration: 	 9
NumTrajs: 	 200
NumTimesteps: 	 39851
Loss:     	 -1.4669430255889893
MaxRew: 	 -450.5044205794205
MeanRew: 	 -594.3661013986016 +- 93.67434871872068
MeanSlowdown: 	 8.223193653176585
MeanLen: 	 199.255 +- 3.945880763530495
MeanEntropy 	 1.4580694
Elapsed time	 132.96890592575073 seconds
-----------------
-----------------
Iteration: 	 10
NumTrajs: 	 200
NumTimesteps: 	 39991
Loss:     	 -0.6385709643363953
MaxRew: 	 -532.5495521145524
MeanRew: 	 -637.0304160006663 +- 95.64422495634686
MeanSlowdown: 	 7.0565866776048525
MeanLen: 	 199.955 +- 0.6348031190849649
MeanEntropy 	 1.3778113
Elapsed time	 127.92189979553223 seconds
-----------------
-----------------
Iteration: 	 11
NumTrajs: 	 200
NumTimesteps: 	 39989
Loss:     	 -0.3427707254886627
MaxRew: 	 -552.0091042291044
MeanRew: 	 -652.8484755244759 +- 103.73894309991317
MeanSlowdown: 	 6.171660689712094
MeanLen: 	 199.945 +- 0.7758704788816234
MeanEntropy 	 1.3164791
Elapsed time	 134.4063766002655 seconds
-----------------
-----------------
Iteration: 	 12
NumTrajs: 	 200
NumTimesteps: 	 40000
Loss:     	 -0.1390867829322815
MaxRew: 	 -575.9448501498504
MeanRew: 	 -667.1217381784885 +- 113.02713584854231
MeanSlowdown: 	 5.653706628379996
MeanLen: 	 200.0 +- 0.0
MeanEntropy 	 1.2678223
Elapsed time	 134.4841344356537 seconds
-----------------
-----------------
Iteration: 	 13
NumTrajs: 	 200
NumTimesteps: 	 40000
Loss:     	 0.0047708721831440926
MaxRew: 	 -599.3291292041293
MeanRew: 	 -685.0703190143194 +- 115.47521020303482
MeanSlowdown: 	 5.758938892920655
MeanLen: 	 200.0 +- 0.0
MeanEntropy 	 1.1377383
Elapsed time	 134.92161464691162 seconds
-----------------
-----------------
Iteration: 	 14
NumTrajs: 	 200
NumTimesteps: 	 40000
Loss:     	 0.24731938540935516
MaxRew: 	 -589.810532800533
MeanRew: 	 -702.4873405760908 +- 109.88026337373238
MeanSlowdown: 	 5.356689487125168
MeanLen: 	 200.0 +- 0.0
MeanEntropy 	 1.0516357
Elapsed time	 135.51561570167542 seconds
-----------------
-----------------
Iteration: 	 15
NumTrajs: 	 200
NumTimesteps: 	 40000
Loss:     	 -0.012406433932483196
MaxRew: 	 -634.9598684648688
MeanRew: 	 -716.9273091908094 +- 114.60784463888714
MeanSlowdown: 	 4.949590315640473
MeanLen: 	 200.0 +- 0.0
MeanEntropy 	 0.993811
Elapsed time	 131.20324039459229 seconds
-----------------
-----------------
Iteration: 	 16
NumTrajs: 	 200
NumTimesteps: 	 40000
Loss:     	 0.2650294601917267
MaxRew: 	 -635.4400932400935
MeanRew: 	 -720.2725810855814 +- 121.37803993918308
MeanSlowdown: 	 4.811817309957675
MeanLen: 	 200.0 +- 0.0
MeanEntropy 	 0.9719665
Elapsed time	 133.84364700317383 seconds
-----------------
-----------------
Iteration: 	 17
NumTrajs: 	 200
NumTimesteps: 	 40000
Loss:     	 0.40593722462654114
MaxRew: 	 -655.0457842157845
MeanRew: 	 -727.2581736596737 +- 124.60043314164538
MeanSlowdown: 	 4.72960476102069
MeanLen: 	 200.0 +- 0.0
MeanEntropy 	 0.9320472
Elapsed time	 133.14540266990662 seconds
-----------------
-----------------
Iteration: 	 18
NumTrajs: 	 200
NumTimesteps: 	 40000
Loss:     	 0.5494382977485657
MaxRew: 	 -653.9862920412922
MeanRew: 	 -728.1601621711625 +- 126.32912398795706
MeanSlowdown: 	 4.611315388518172
MeanLen: 	 200.0 +- 0.0
MeanEntropy 	 0.9108092
Elapsed time	 133.32872080802917 seconds
-----------------
-----------------
Iteration: 	 19
NumTrajs: 	 200
NumTimesteps: 	 40000
Loss:     	 0.12479257583618164
MaxRew: 	 -653.9319513819516
MeanRew: 	 -726.4651829836833 +- 129.42491083581248
MeanSlowdown: 	 4.668638181757777
MeanLen: 	 200.0 +- 0.0
MeanEntropy 	 0.88868874
Elapsed time	 131.6566641330719 seconds
-----------------
-----------------
Iteration: 	 20
NumTrajs: 	 200
NumTimesteps: 	 40000
Loss:     	 0.22364497184753418
MaxRew: 	 -656.912790542791
MeanRew: 	 -731.9332774725277 +- 139.63200197824418
MeanSlowdown: 	 4.763752324495952
MeanLen: 	 200.0 +- 0.0
MeanEntropy 	 0.8378573
Elapsed time	 132.31217503547668 seconds
-----------------
-----------------
Iteration: 	 21
NumTrajs: 	 200
NumTimesteps: 	 40000
Loss:     	 0.1732483059167862
MaxRew: 	 -659.6613136863139
MeanRew: 	 -723.9488101898106 +- 144.69374078172066
MeanSlowdown: 	 4.949693603384104
MeanLen: 	 200.0 +- 0.0
MeanEntropy 	 0.64697117
Elapsed time	 131.07797598838806 seconds
-----------------
-----------------
Iteration: 	 22
NumTrajs: 	 200
NumTimesteps: 	 40000
Loss:     	 -0.1176895722746849
MaxRew: 	 -663.2200466200468
MeanRew: 	 -735.3471840659345 +- 144.99045204341766
MeanSlowdown: 	 5.245480022956364
MeanLen: 	 200.0 +- 0.0
MeanEntropy 	 0.47314718
Elapsed time	 134.04664516448975 seconds
-----------------
-----------------
Iteration: 	 23
NumTrajs: 	 200
NumTimesteps: 	 40000
Loss:     	 -0.032905176281929016
MaxRew: 	 -690.9420862470866
MeanRew: 	 -749.255551448552 +- 140.83590257882247
MeanSlowdown: 	 5.0925722362864
MeanLen: 	 200.0 +- 0.0
MeanEntropy 	 0.39582643
Elapsed time	 131.21907782554626 seconds
-----------------
-----------------
Iteration: 	 24
NumTrajs: 	 200
NumTimesteps: 	 40000
Loss:     	 0.15587106347084045
MaxRew: 	 -691.3202580752586
MeanRew: 	 -754.2126247918754 +- 149.2469613204072
MeanSlowdown: 	 4.6995492490678625
MeanLen: 	 200.0 +- 0.0
MeanEntropy 	 0.33751372
Elapsed time	 132.625061750412 seconds
-----------------

D:/RL_ENVIRONMENT_SCHEDULER/REINFORCE_AGENT.PY:32: RUNTIMEWARNING: DIVIDE BY ZERO ENCOUNTERED IN LOG
  ENTROPY = - NP.SUM(VEC * NP.LOG(VEC))
D:/RL_ENVIRONMENT_SCHEDULER/REINFORCE_AGENT.PY:32: RUNTIMEWARNING: INVALID VALUE ENCOUNTERED IN MULTIPLY
  ENTROPY = - NP.SUM(VEC * NP.LOG(VEC))
  
-----------------
Iteration: 	 25
NumTrajs: 	 200
NumTimesteps: 	 40000
Loss:     	 0.2555212676525116
MaxRew: 	 -684.3491108891113
MeanRew: 	 -765.4223881118887 +- 155.46034687865773
MeanSlowdown: 	 4.564588823278404
MeanLen: 	 200.0 +- 0.0
MeanEntropy 	 0.30876887
Elapsed time	 133.49998474121094 seconds
-----------------
-----------------
Iteration: 	 26
NumTrajs: 	 200
NumTimesteps: 	 40000
Loss:     	 0.2262439876794815
MaxRew: 	 -700.0753912753919
MeanRew: 	 -767.26688927739 +- 164.1536290780541
MeanSlowdown: 	 4.500758152915268
MeanLen: 	 200.0 +- 0.0
MeanEntropy 	 0.31221923
Elapsed time	 132.8123459815979 seconds
-----------------
-----------------
Iteration: 	 27
NumTrajs: 	 200
NumTimesteps: 	 40000
Loss:     	 0.16316479444503784
MaxRew: 	 -710.2259607059613
MeanRew: 	 -770.4424490509497 +- 164.24869263674503
MeanSlowdown: 	 4.431473687602721
MeanLen: 	 200.0 +- 0.0
MeanEntropy 	 0.3087118057273328
Elapsed time	 132.2345860004425 seconds
-----------------
-----------------
Iteration: 	 28
NumTrajs: 	 200
NumTimesteps: 	 40000
Loss:     	 0.2970004379749298
MaxRew: 	 -696.8189294039299
MeanRew: 	 -768.8670524475532 +- 172.14244134967433
MeanSlowdown: 	 4.4497024278979165
MeanLen: 	 200.0 +- 0.0
MeanEntropy 	 0.2989954816605896
Elapsed time	 131.29700684547424 seconds
-----------------
-----------------
Iteration: 	 29
NumTrajs: 	 200
NumTimesteps: 	 40000
Loss:     	 0.3338070809841156
MaxRew: 	 -694.4622627372634
MeanRew: 	 -764.0287954545462 +- 174.10062722713732
MeanSlowdown: 	 4.3739770244062095
MeanLen: 	 200.0 +- 0.0
MeanEntropy 	 0.3329050304107368
Elapsed time	 134.265775680542 seconds
-----------------
-----------------
Iteration: 	 30
NumTrajs: 	 200
NumTimesteps: 	 40000
Loss:     	 0.3740381896495819
MaxRew: 	 -683.796686646687
MeanRew: 	 -771.2451685814193 +- 166.92956159658652
MeanSlowdown: 	 4.466197944666277
MeanLen: 	 200.0 +- 0.0
MeanEntropy 	 0.294103304207325
Elapsed time	 125.43745565414429 seconds
-----------------
-----------------
Iteration: 	 31
NumTrajs: 	 200
NumTimesteps: 	 40000
Loss:     	 0.4445381760597229
MaxRew: 	 -692.0301415251422
MeanRew: 	 -773.1652278554786 +- 171.17519887739007
MeanSlowdown: 	 4.53933822063667
MeanLen: 	 200.0 +- 0.0
MeanEntropy 	 0.32781646759063005
Elapsed time	 133.29682087898254 seconds
-----------------
-----------------
Iteration: 	 32
NumTrajs: 	 200
NumTimesteps: 	 40000
Loss:     	 0.8396180868148804
MaxRew: 	 -673.557054612055
MeanRew: 	 -774.1230308857815 +- 159.5705089948694
MeanSlowdown: 	 4.515589160351684
MeanLen: 	 200.0 +- 0.0
MeanEntropy 	 0.3873567596077919
Elapsed time	 131.25004172325134 seconds
-----------------
-----------------
Iteration: 	 33
NumTrajs: 	 200
NumTimesteps: 	 40000
Loss:     	 -10.721101760864258
MaxRew: 	 -958.0317932067937
MeanRew: 	 -1285.27405977356 +- 410.5646749576981
MeanSlowdown: 	 17.460779093810462
MeanLen: 	 200.0 +- 0.0
MeanEntropy 	 0.32193423502892254
Elapsed time	 130.17177510261536 seconds
-----------------
-----------------
Iteration: 	 34
NumTrajs: 	 200
NumTimesteps: 	 40000
Loss:     	 -3.512230157852173
MaxRew: 	 -2056.163463203464
MeanRew: 	 -2294.4768547286053 +- 435.3744306761525
MeanSlowdown: 	 32.70494624653232
MeanLen: 	 200.0 +- 0.0
MeanEntropy 	 0.10786593561805785
Elapsed time	 130.35966539382935 seconds
-----------------
-----------------
Iteration: 	 35
NumTrajs: 	 200
NumTimesteps: 	 40000
Loss:     	 -0.6767964959144592
MaxRew: 	 -2369.3911971361986
MeanRew: 	 -2445.489590159841 +- 463.0411101783617
MeanSlowdown: 	 48.404853479853486
MeanLen: 	 200.0 +- 0.0
MeanEntropy 	 0.060548943658999634
Elapsed time	 129.06213974952698 seconds
-----------------
-----------------
Iteration: 	 36
NumTrajs: 	 200
NumTimesteps: 	 40000
Loss:     	 -0.051592279225587845
MaxRew: 	 -2453.9599317349325
MeanRew: 	 -2469.5031471028983 +- 494.26187256819975
MeanSlowdown: 	 83.0
MeanLen: 	 200.0 +- 0.0
MeanEntropy 	 0.04461172729887767
Elapsed time	 134.56257271766663 seconds
-----------------
-----------------
Iteration: 	 37
NumTrajs: 	 200
NumTimesteps: 	 40000
Loss:     	 -0.10192881524562836
MaxRew: 	 -2441.562031302032
MeanRew: 	 -2469.5631471028983 +- 494.5614176992619
MeanSlowdown: 	 83.33333333333333
MeanLen: 	 200.0 +- 0.0
MeanEntropy 	 0.03867417912872588
Elapsed time	 128.5938630104065 seconds
-----------------
-----------------
Iteration: 	 38
NumTrajs: 	 200
NumTimesteps: 	 40000
Loss:     	 8.5104518350676635e-16
MaxRew: 	 -2471.257832167833
MeanRew: 	 -2471.257832167833 +- 497.23920232364605

C:\USERS\IUSTACK\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON37\LIB\SITE-PACKAGES\NUMPY\CORE\FROMNUMERIC.PY:3335: RUNTIMEWARNING: MEAN OF EMPTY SLICE.
  OUT=OUT, **KWARGS)
  
MeanSlowdown: 	 nan
MeanLen: 	 200.0 +- 0.0
MeanEntropy 	 0.034907410109136665
Elapsed time	 135.28876852989197 seconds
-----------------
`

**Comment by hongzimao** [comment]
The elapsed time looks similar to what we had in the last experiment -- I remember setting up a week long experiment to get the final result for the paper. We didn't do much optimization for this code. If you want quicker turnaround, you can try reduce the problem size (smaller `num_ex` and `num_nw`, smaller network and smaller `simu_len`).

**Comment by ahmadreza9** [comment]
> I remember setting up a week long experiment to get the final result for the paper

Jesus :). Sir, what is main contribution compared to meta heuristics like PSO. What did make you disregard them?
