### ISSUE TITLE
Multiple machines

### ISSUE THREAD

**Issue by sucui-work** [hongzimao/deeprm#13]
Hi,
I'd like to test some scheduling algorithms on multiple machines. How to pick number of machines ranging from 1 to 5 in the code?
Thanks,

**Comment by AluriJaganMohini** [comment]
This particular repository  

> https://github.com/BrightFeather/deeprm2 

is working with deeprm using the multiple machines. It might be helpful for you.

**Comment by sucui-work** [comment]
Thank you!
