### ISSUE TITLE
It takes about 5 minutes to finish one epoch...

### ISSUE THREAD

**Issue by xiechengsheng** [hongzimao/deeprm#2]
Hi, I have read your paper and want to have a try. but when I run the demo's command, the training process seems to be very slow.
The demo's command:
```
# python launcher.py --exp_type=pg_su --simu_len=50 --num_ex=1000 --ofile=data/pg_su --out_freq=10
``` 
And here is the output log:
```
Epoch 1 of 10000 took 297.221s
  training loss:    		0.838964
  training accuracy:		78.30 %
  test loss:        		0.802981
  test accuracy:    		79.96 %
...
```
So if each epoch costs 5 minutes, the whole 10000 epoches will cost about **one month**. Is this normal? 
And When I ran the command, I found the process only cost my server machine **one physical core**, this seemed to be the key of the slow training process problem.
Any suggestion to make the training process faster? Or is there anything wrong with my understanding about the training process?
Thanks in advance!

**Comment by hongzimao** [comment]
This looks suspicious -- `--exp_type=pg_su` means supervised learning and it shouldn't be this slow. I remember the code runs much faster on my laptop (and some other machines as well). You can try to reduce `--num_ex=10` and debug if there's anything wrong. Also, keep in mind that supervised learning doesn't have to take 10000 epochs to converge.

Regard to multi-core speed up, `pg_re.py` has multi-processing implementation (as opposed to `pg_re_single_core.py`).

**Comment by xiechengsheng** [comment]
1. Thanks for your apply.
2. I rerun the command on another machine, and this time the training process actually costs the machine's whole cores(8 cores). But it seems useless. The training process speed improves little:joy:. 

The training log:
```
Epoch 1 of 10000 took 192.522s
  training loss:    		0.838618
  training accuracy:		78.28 %
  test loss:        		0.805027
  test accuracy:    		79.54 %
```

The top command's output:
```
 PID  USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                      
11406 root      20   0 1219028 125624  17888 R 798.0  0.5  10:19.69 python                                                                  
```
3. I will try to set `--num_ex` to 10 to run the program~

**Comment by hongzimao** [comment]
Like I said, the supervised learning doesn't use multiprocessing to speed things up -- the 8 core utilization is probably underlining theano optimization, which does work, but not comparable with main program parallelism.

**Comment by AditiKatiyar** [comment]
I am getting an 'Ubuntu internal error' when I run the program. Can anyone help, please?

**Comment by xiechengsheng** [comment]
Please make sure that your dependent python library version is consistent with the version provided by the author.

**Comment by AditiKatiyar** [comment]
Thanks a lot.
